-- Create Rooms Table
create table public.rooms (
  id text primary key,
  created_at timestamptz default now(),
  status text check (status in ('lobby', 'playing', 'finished')) default 'lobby',
  game_type text check (game_type in ('scipher', 'wavelength')) default 'scipher',
  current_round int default 1,
  total_rounds int default 12,
  round_length int default 60,
  turn_team text check (turn_team in ('neon', 'cyber')) default 'neon',
  turn_describer_id uuid,
  turn_end_time timestamptz,
  current_word jsonb,
  scores jsonb default '{"neon": 0, "cyber": 0}'::jsonb,
  wavelength_state jsonb,
  last_updated timestamptz default now()
);

-- Create Players Table
create table public.players (
  id uuid primary key default gen_random_uuid(),
  room_id text references public.rooms(id) on delete cascade,
  name text not null,
  team text check (team in ('neon', 'cyber')),
  is_host boolean default false,
  stats jsonb default '{"guessed": 0, "points": 0, "best_describer_points": 0}'::jsonb,
  created_at timestamptz default now()
);

-- Create Messages Table
create table public.messages (
  id bigint generated by default as identity primary key,
  room_id text references public.rooms(id) on delete cascade,
  player_id uuid references public.players(id) on delete set null,
  player_name text,
  content text not null,
  created_at timestamptz default now(),
  type text check (type in ('chat', 'system', 'guess_correct')) default 'chat',
  team text check (team in ('neon', 'cyber'))
);

-- Enable Realtime
alter publication supabase_realtime add table public.rooms;
alter publication supabase_realtime add table public.players;
alter publication supabase_realtime add table public.messages;

-- RLS Policies (Open for prototype simplicity, but good practice to have)
alter table public.rooms enable row level security;
alter table public.players enable row level security;
alter table public.messages enable row level security;

-- Allow anyone to read/write for now (since we use anonymous auth or just client-side ID)
create policy "Public Access Rooms" on public.rooms for all using (true) with check (true);
create policy "Public Access Players" on public.players for all using (true) with check (true);
create policy "Public Access Messages" on public.messages for all using (true) with check (true);
